### ISSUE TITLE
Rework the `patterns!` macro to re-de-duplicate logic

### ISSUE THREAD

**Issue by str4d** [AccessKit/accesskit#104]
The `patterns!` macro previously both generated the `ResolvedPlatformNode::pattern_provider` and `ResolvedPlatformNode::enqueue_pattern_property_changes` methods, and also generated some of the boilerplate methods for the `#[implement(_)]` derivations from the `windows` crate.

In `windows 0.32` the `implement` macro was reworked to use traits (https://github.com/microsoft/windows-rs/pull/1450). As a result, we can't just derive the methods for all patterns in the existing `patterms!` macro invocation, because:
- The per-trait methods need to go into separate `impl IFooBarProvider_Impl for FooBarProvider` trait impls.
- The patterns are a subset of the trait methods that need to be implemented.

In #102 I took the simple approach of duplication: we now manually implement the boilerplate methods in addition to specifying their details inside the `patterns!` macro. It would be nice to figure out how to rework the `patterns!` macro to re-introduce the previous de-duplication.

**Comment by str4d** [comment]
Aaand the moment I wrote this issue, I figured out how to do this nicely 😄 I'll update #102 with this.

**Comment by DataTriny** [comment]
Fixed by #102.
