### ISSUE TITLE
Optimize memory usage of data structures

### ISSUE THREAD

**Issue by mwcampbell** [AccessKit/accesskit#11]
The structures defined in the schema scrate haven't yet been optimized for memory usage. In particular, the `Node` struct is ~1.5KB on a 64-bit machine.

**Comment by i509VCB** [comment]
From running `cargo +nightly rustc -p accesskit -- -Zprint-type-sizes`, this is a breakdown of the size of `Node`:

https://gist.github.com/i509VCB/c15dfb11b3804cdbd82a28b5e90b3df8
