### ISSUE TITLE
winit integration

### ISSUE THREAD

**Issue by mwcampbell** [AccessKit/accesskit#117]
Some popular Rust GUI toolkits and game engines use [winit](https://github.com/Rust-Windowing/winit), so we need an easy way for winit-based applications to use AccessKit.

On Windows, the issue is that winit doesn't currently provide an official way for users to handle custom window messages such as `WM_GETOBJECT`. Possible fixes for this have been discussed on Rust-Windowing/winit#2120, but nothing has yet been implemented. That's not a complaint; I'm sure everyone working on winit is busy with other things. But I need to implement a solution soon. So I'm going to use a Win32 API technique called subclassing to override the window procedure with our own message handler. I'll implement this in the `accesskit_windows` crate, then I can add an `accesskit_winit` crate.

**Comment by mwcampbell** [comment]
I implemented Win32 subclassing in #118.

**Comment by mwcampbell** [comment]
My new winit adapter is in [the winit branch under platforms/winit](https://github.com/AccessKit/accesskit/tree/winit/platforms/winit). I'll submit a PR once #120 is reviewed.

**Comment by maroider** [comment]
The use of a `T: From<ActionRequestEvent>` on the `ActionHandler` impl for `WinitActionHandler<T>` honestly surprised me (in a good way, of course). The API quite reasonable to me, given the current state of Winit's.

**Comment by mwcampbell** [comment]
I just published the accesskit_winit crate on crates.io. So I'll close this, and open separate issues for any problems that arise in real-world usage.
