### ISSUE TITLE
How can at-spi2-core notify accesskit about XML changes?

### ISSUE THREAD

**Issue by federicomenaquintero** [AccessKit/accesskit#188]
I'm in the process of doing several things more or less at the same time:

* [documenting](https://gitlab.gnome.org/GNOME/at-spi2-core/-/issues/69) the [dbus XML interfaces in at-spi2-core](https://gitlab.gnome.org/GNOME/at-spi2-core/-/tree/main/xml)
* [Fixing incorrect method signatures](https://gitlab.gnome.org/GNOME/at-spi2-core/-/issues/75) as part of [making the XML the single source of truth](https://gitlab.gnome.org/GNOME/at-spi2-core/-/issues/73)

The result is that the dbus XML files in at-spi2-core **are changing** to reflect what the C code actually does.  Bindings that use the XML as a basis will of course want to be notified of this.

So, this issue is me asking you for how to best communicate this.

I can file a bug report here every time I make a change, but this doesn't help other projects (e.g. GTK4, WebKit) that also use DBus directly instead of atk.

(Concretely, my latest fix is in [this commit](https://gitlab.gnome.org/federico/at-spi2-core/-/commit/9096b760c8d8295874c1b1ed37c920634739912b) - not merged yet, hopefully in a merge request soon.)

**Comment by mwcampbell** [comment]
I'll defer to @DataTriny on this, since he's doing most of the work on the AT-SPI backend. Note that, as he mentioned on the other issue, that backend is using the [atspi crate](https://crates.io/crates/atspi), which is primarily developed by the Odilia team, as much as possible.

**Comment by federicomenaquintero** [comment]
Filed at https://github.com/odilia-app/atspi/issues/22

**Comment by DataTriny** [comment]
I have mostly used the C code as reference for now, so I think what we use reflects what at-spi2-core expects.

For the future, maintaining a changelog document would really help. Still, since we currently have no way of specifying which version of the AT-SPI protocol we support, I assume that there will always be broken stuff if at-spi2-core evolves frequently.

**Comment by mwcampbell** [comment]
Does this need to remain an open issue, or has the question been answered?
