### ISSUE TITLE
TextField characters not read by screen reader on Windows 11

### ISSUE THREAD

**Issue by geom3trik** [AccessKit/accesskit#189]
While integrating AccessKit with my own GUI lib, using the egui integration as reference, I noticed that narrator (the screen reader I am using for testing) is not working correctly with a textbox (TextField role with InlineTextBox child). The characters are not read when shifting the cursor with the arrow keys or when selecting the text. To make sure this wasn't a problem on my end I ran the egui example and found the same problem.

I don't know if this problem is specific to Windows 11 but I can check on a Windows 10 machine tomorrow.

**Comment by spencerudnick** [comment]
This coincides with my own experience trying to implement `ITextRangeProvider`. I'm curious how things work for you on Windows 10.

@geom3trik does Narrator say anything at all? Does it read the label of the text field correctly?
