### ISSUE TITLE
accesskit_winit 0.12.5 breaks semantic versioning

### ISSUE THREAD

**Issue by james7132** [AccessKit/accesskit#233]
`accesskit_winit` bumped the `accesskit` dependency from 0.10.1 (in 0.12.3) to 0.11.0 (in 0.12.5) in a patch release. This is a breaking change, particularly since accesskit's types are in the public interface of accesskit_winit. This should have been done as a part of a minor version update instead.

This is causing Bevy to have duplicate accesskit dependencies in recent builds. Could 0.12.5 be yanked and a 0.13.0 published in its stead?

EDIT: This has been filed under https://github.com/bevyengine/bevy/issues/8258.

**Comment by mwcampbell** [comment]
OK, I yanked 0.12.5.

**Comment by mwcampbell** [comment]
OK, I published accesskit_winit 0.13.0. I also did a minor version bump for all other dependents of the accesskit crate.
