### ISSUE TITLE
Split platform specific "C"-bindings into the separate files

### ISSUE THREAD

**Issue by bruvzg** [AccessKit/accesskit#242]
Currently, `accesskit.h` includes some Obj-C headers when it is used on macOS, therefore it is usable only from the Obj-C/Obj-C++ source, but not from pure C/C++.

Splitting platform specific adapter bindings to the separate file would allow using platform independent part of the code from C/C++.

Or alternatively, since no Obj-C specific stuff is really used in the binding, it might be worth getting rid of the Obj-C includes, by replacing `NSObject *` with `void *` (already done with `NSView *` for subclassing adapter) and `CGPoint` with two floats.

**Comment by DataTriny** [comment]
Thanks @bruvzg for the report.

I thought this could work.

We will go the second path then, as there is not an easy way to generate multiple header files with cbindgen.
