### ISSUE TITLE
Add a CONTRIBUTING.md ?

### ISSUE THREAD

**Issue by paul-hansen** [AccessKit/accesskit#268]
Just a minor suggestion. A CONTRIBUTING.md or something along those lines might be helpful after running into these things that were non-obvious to me working on #257:
- Why we have a Cargo.lock file
- When should the Cargo.lock file be updated
- Changelog should not be modified. Instead use ?? (something to do with release-please, I don't understand it yet)
- How to run tests locally
   - run `cargo test -p accesskit_windows` in addition to `cargo test`
   - Note that some tests may fail if the window looses focus. Try running directly from terminal instead of from your IDEs terminal
   
If desired, I could make an initial draft based on these points, but if someone that works on the project regularly has time, they might have better knowledge of what should be in it.

**Comment by mwcampbell** [comment]
I need to work on something else now, but I just wanted to say thanks for your suggestion, for bearing with us as we figure out how best to bring new contributors up to speed, and for your PR.

**Comment by DataTriny** [comment]
Indeed this is a very good idea. Thanks for bringing it up. If you want to start a draft, I'll gladly help you. In fact this is the kind of documents best produced by people without inside knowledge.

BTW I think you already nailed the most important points!
