### ISSUE TITLE
Implement UIA provider properties

### ISSUE THREAD

**Issue by leonardder** [AccessKit/accesskit#280]
For cleanliness, I think it would be nice if UIA properties would be implemented that allow UIA elements to be identified as coming from accesskit:

* FrameworkIdProperty: Probably just `AccessKit`
* ProviderDescriptionProperty: I'm not sure how this one is used, but it might be beneficial to provide version information of the accesskit_windows crate

Probably pretty trivial, but I think this can could be considered an issue a new developer can start with 😉
I guess there can some debate about whether an user of the crate can update both properties, for example to communicate that the element is coming from their framework.

**Comment by DataTriny** [comment]
We already support exposing this information on Unix, as can be seen in the [C bindings SDL example](https://github.com/AccessKit/accesskit/blob/main/bindings/c/examples/sdl/hello_world.c). We prefer advertising the GUI toolkit's name and version, rather than AccessKit itself though.

**Comment by leonardder** [comment]
That's perfectly fine with me as well of course. I"ll have a look.
