### ISSUE TITLE
A more concise project tagline

### ISSUE THREAD

**Issue by mwcampbell** [AccessKit/accesskit#340]
The current sub-heading in the README, "UI accessibility infrastructure across platforms and programming languages", is a bit verbose. The tagline written by the contractor who did the current AccessKit.dev site, "A True Universal Access Solution", is too vague and untargeted for my taste. So I propose: "Accessibility for your UI toolkit." I think this tagline makes it clear that this project is primarily for toolkit developers, not application developers, while still conveying our ambition to be universal within that space.

**Comment by DataTriny** [comment]
Although a bit long, I like what we currently have. What you propose is also fine, I'm on-board if you want to update it.

What is written on the website definitely need to be changed that's for sure.

**Comment by DataTriny** [comment]
You'll have to update the repository description as well, why not take this as an opportunity to add appropriate topics while at it?
