### ISSUE TITLE
Update `windows` crate

### ISSUE THREAD

**Issue by emilk** [AccessKit/accesskit#350]
https://github.com/AccessKit/accesskit/blob/main/platforms/windows/Cargo.toml is stuck on 0.48

It would be nice if a range of versions could be supported, because that would make it less likely that users will get duplicates of `windows` (which is a huge crate that compiles very slowly)

**Comment by DataTriny** [comment]
Hello @emilk,

AccessKit doesn't compile with windows v1.51 so a version range wouldn't help here. I think we made substancial changes when we updated to 1.48 so a range allowing older versions is probably not feasible either. We might just need to update to 1.52, as it's three months old now.
