### ISSUE TITLE
Aspiring Contributor Questions

### ISSUE THREAD

**Issue by maniyar1** [AccessKit/accesskit#355]
Hello :slightly_smiling_face:, I would like to contribute to accesskit, but I'm a bit unsure where to start. There are some older issues from 2021 that seem doable. I don't want to ask too much labor from maintainers, so I have two quick questions:

1) Could accesskit use a (very part time) contributor? (No is okay!)
2) If so, can someone point me to a good starting issue that no one else is not currently working on for me to try my hand at? Something not super important :laughing:?

If there's anything documentation-oriented I would love to do that. Even if there's no issues, I'd be happy to go through and write tutorials/examples, if that would be useful. 

Thank you!

**Comment by mwcampbell** [comment]
Hi @maniyar1. Thanks for your interest in contributing. It would help to know what previous experience, if any, you have with accessibility, native desktop APIs (e.g. Win32 and Cocoa), or both. Thanks again.

**Comment by maniyar1** [comment]
I have experience writing accessible web interfaces using semantic HTML + Aria tags. I have a testing setup for that, which obviously involves a screen reader and adjacent technology. I try to keep up with UX design elements on that side of things. I have experience in Rust, but not really any substantial experience with native desktop APIs. I mostly work on the Linux side of things, so my experience is with x11/wayland/gtk/qt. But even that experience is mostly as a user. I also have a writing background, wherever that is useful.

**Comment by mwcampbell** [comment]
I'm afraid the remaining open issues from 2021 are things for someone who's familiar with UI Automation and Windows screen readers. They're on my roadmap for sometime this year.

But here's an idea: identify a GUI toolkit that isn't yet accessible, implement AccessKit support in that toolkit, and document the process. We need more documentation, and a document describing the process of making a GUI toolkit accessible from scratch would be especially useful. It could be a Rust, C, or C++ toolkit (we don't have a direct C++ API yet, but we do have a C API).

It would probably be better to do your testing on Windows or macOS if you can. The Linux backend is not as complete as the other two.

**Comment by maniyar1** [comment]
Sounds good! I will try my hand at that. I'll close this issue and open a new one for that specifically, if that sounds good?

**Comment by mwcampbell** [comment]
OK, I'm closing this issue. Feel free to open a new one.

**Comment by DataTriny** [comment]
Hi @maniyar1, thanks for stopping by.

One of my short-term projects is to integrate AccessKit into [kivy](https://github.com/kivy/kivy) to demonstrate the capabilities of our Python bindings.

If you'd like a guided introduction to AccessKit, we could work on this together. If you're interested or if you have questions on that, feel free to reach out to me directly either on Discord (same username) or via email (available on my GitHub profile).

If you prefer to experiment on your own, it's also fine!
