### ISSUE TITLE
Contrast too low for headings on the accesskit.dev website

### ISSUE THREAD

**Issue by DominoPivot** [AccessKit/accesskit#445]
I'll keep it short: many pages on https://accesskit.dev/ use dark grey over black (#333333 over #000000) for their level 1 heading. I'm sure this slipped through because maintaining the website is very low priority, but having contrast issues on the home page for an accessibility toolkit gives a bad first impression.

I'm not sure where would have been the most practical place to report this. I'll ping someone on Fostodon if this doesn't get noticed.

PS — The site's logo is also crushed vertically when the site is viewed on a wide screen.

**Comment by mwcampbell** [comment]
Thanks for the report. I want to completely redo the AccessKit.dev site, replacing the current WordPress site with something lighter, probably generated with a static site generator. I don't like the current site myself.

**Comment by DataTriny** [comment]
Thank you @DominoPivot for this bug report.

We have just launched a new version of the [accesskit.dev](https://accesskit.dev) website. The new design should be accessible to a wider audience.

If you encounter further issues, please report them on [the website's repository](https://github.com/AccessKit/accesskit-website).
