### ISSUE TITLE
Should `Role::GenericContainer` translate to AT-SPI's `Panel` role?

### ISSUE THREAD

**Issue by Tropix126** [AccessKit/accesskit#455]
Currently `Role::GenericContainer` is treated as an AT-SPI `Role::Section`, which is described as such:

> The object is a containing instance of document content which constitutes a particular ‘logical’ section of the document. The type of content within a section, and the nature of the section division itself, may be obtained by querying the object’s attributes. Sections may be nested.

https://github.com/AccessKit/accesskit/blob/96a7ca2a458a2712dddb2ac3459861ab93ed04be/platforms/atspi-common/src/node.rs#L151

This seems to imply that the section role at least could have some semantic meaning to consumers (being a "logical section of the document"). While digging through what a `GenericContainer` actually entails (it seems like it's possibly useful to magnifiers due to providing layout information about a node), I came across ATSPI's [`Panel` role](https://docs.rs/atspi-common/latest/atspi_common/enum.Role.html#variant.Panel) which, based on the description, seems to fit the purpose of `GenericContainer` much better.

> A generic container that is often used to group objects.

Any thoughts on this? I have no experience using AT-SPI or any platform-native a11y API directly, but it seemed to be worth bringing up here.

**Comment by DataTriny** [comment]
Hello @Tropix126,

In practice, nodes with `Role::GenericContainer` are filtered out, and don't end up in the platform's accessibility tree. Unlike nodes with `Role::Group` or `Role::Pane` for instance, which are mapped to the AT-SPI Panel role.

**Comment by DataTriny** [comment]
@Tropix126 Did I answer your question?

**Comment by Tropix126** [comment]
> @Tropix126 Did I answer your question?
Yeah, that makes sense. Closing.
