### ISSUE TITLE
MacOS adapter and the Accessibility Inspector

### ISSUE THREAD

**Issue by HolgerGottChristensen** [AccessKit/accesskit#465]
I have been working on integrating access kit into my personal project, and is currently mainly focusing on MacOS.

When I run the example "simple.rs" from the accesskit_winit crate, and look in the accessibility inspector app, i have a few problems. 

When I start the accessibility inspector first, and then run "simple.rs" the process does not show up in the list of running applications. Other apps show up in the list after I open them.
<img width="711" alt="Screenshot 2024-10-13 at 14 47 27" src="https://github.com/user-attachments/assets/0a9c4fc2-8cec-4a9c-ad93-ee4c272f8c70">

The second issue is when I inspect the application, it contains no data on the accessibility
<img width="748" alt="Screenshot 2024-10-13 at 14 46 22" src="https://github.com/user-attachments/assets/fc2918cc-64c4-4361-ae27-56da39eed888">

The third issue is when I inspect another application and then go back to the "simple.rs" application, it does not override the information in the inspector. Only when I go to "simple.rs" again it clears the data.
https://github.com/user-attachments/assets/33db9317-923c-4bfe-b008-238f0f9e081f

I am guessing all the issues above are related, and have to do with the way the macOS adapter is created.
The first thing I have noticed looking at the code, is that the adapter is currently tied to a NSWindow (through its NSView).
This means we have no accessibility node on the NSApplication (the root of the program). I am guessing the accessibility inspector is looking at the applications with accessibility by looking at the root of the programs.

How do I get an accessibility node on the NSApplication, and assign the windows as children of that node? 

Is there a specific reason that the adapter is tied to the window and not the application on macOS? 

I am not sure if other platforms expect the adapter to be tied to individual windows, and not the root application? 

I would love to help resolving the issue if help is needed, but I am not sure the best way to resolve the problem.

**Comment by mwcampbell** [comment]
Hi @HolgerGottChristensen. Thank you for your interest in accessibility and AccessKit.

Another toolkit developer also ran into issues with the macOS accessibility inspector. We discovered that for an application to show up in the inspector, it needs to be packaged and run as a macOS app bundle, not simply run from the terminal. If you're not creating an app bundle yet, one way to do so is with [cargo-bundle](https://crates.io/crates/cargo-bundle).

**Comment by HolgerGottChristensen** [comment]
The application does show up, but does not show any accessibility information. Do you know if the other toolkit developer had the same problem?

**Comment by mwcampbell** [comment]
I'm sorry, I've forgotten the details. I just remember that it didn't work until the app was run from a packaged macOS app bundle.

**Comment by HolgerGottChristensen** [comment]
Ok I just tested it, and it does indeed work when I bundled the application.

<img width="624" alt="Screenshot 2024-10-13 at 15 28 59" src="https://github.com/user-attachments/assets/f38a621a-3aa3-4842-89bb-c283d864ea69">

Thank you for your help :D
