### ISSUE TITLE
MacOS Adapter - Sub roles

### ISSUE THREAD

**Issue by HolgerGottChristensen** [AccessKit/accesskit#477]
I have been trying to implement accessibility for some of my controls, and is currently comparing the accessiblity tree generated from my application, and from the equivalent SwiftUI application. 

When implementing accessibility for checkboxes, toggle buttons and switches, i noticed the accessibility tree generated by SwiftUI uses the role CheckBox for all the three controls, but with different sub roles.

https://developer.apple.com/documentation/appkit/nsaccessibilitysubrole?language=objc

How is it intended to implement these using AccessKit? I see AccessKit specifies CheckBox and Switch as different roles, but I see no role equivalent to the toggle button.

I can also see when the Switch and CheckBox roles from AccessKit are used, they both set the NSAccessibilityRole CheckBox, but no sub role.

## Toggle button from SwiftUI

<img width="769" alt="Screenshot 2024-10-29 at 21 16 28" src="https://github.com/user-attachments/assets/ade0022c-10e1-49c3-b27c-9d48d94dd0ac">

## Checkbox from SwiftUI

<img width="764" alt="Screenshot 2024-10-29 at 21 17 13" src="https://github.com/user-attachments/assets/adc240ed-aa7e-4351-b25d-6ba590637074">

## Toggle from SwiftUI

<img width="763" alt="Screenshot 2024-10-29 at 21 18 04" src="https://github.com/user-attachments/assets/797f1c90-3633-44af-b5a3-73292bcf96e8">

**Comment by DataTriny** [comment]
Thank you @HolgerGottChristensen for digging into this. We currently don't implement sub roles. I actually investigated this for #372 but forgot to write about it.

**Comment by DataTriny** [comment]
We need to implement the `accessibilitySubrole` method like Chromium does.

**Comment by HolgerGottChristensen** [comment]
Adding support for sub roles would solve part of my problem. I can make a pull request for this feature, but maybe you have some code in chromium I should base it on?

The second part of my problem is now solved directly by implementing sub roles. As I understand it AccessKit contain roles for Switch and Checkbox, but not for toggle button. Would you be interested in adding a new AccessKit role for toggle buttons, or should this be implemented in some kind of extension?

**Comment by mwcampbell** [comment]
In AccessKit, we express toggle buttons by using the `Button` role and setting the toggle state. The rationale for not having a separate `ToggleButton` role is that it's redundant. If we had a `ToggleButton` role, then two illegal states would be representable: a `ToggleButton` role but no toggle state, and a `Button` role with a toggle state. So the platform adapter should map the combination of a `Button` role and a toggle state to a toggle button role or subrole if applicable.

**Comment by HolgerGottChristensen** [comment]
Perfect, I knew I must have missed something😃 

I will create a pull request in the upcoming days. Do you want the implementation based on some chromium code?

**Comment by mwcampbell** [comment]
Feel free to look at Chromium code if it clarifies anything for you, but we've diverged from Chromium at this point, and you may be able to figure out a straightforward mapping on your own.

**Comment by DataTriny** [comment]
Looking at Chromium's mapping will save you time. As you can see not all subroles are documented by Apple and Chromium developers had to find the string values on their own.

With that being said, some subroles exist and you should use them instead of raw strings. In your specific case, you are looking for [`NSAccessibilitySwitchSubrole`](https://docs.rs/objc2-app-kit/latest/objc2_app_kit/static.NSAccessibilitySwitchSubrole.html) and [`NSAccessibilityToggleSubrole`](https://docs.rs/objc2-app-kit/latest/objc2_app_kit/static.NSAccessibilityToggleSubrole.html).
